/**
 * 模擬api SPEC11060101-理財妙管家
 */

let response = {

    apiId: "SPEC11060101",
    token: {
        requestId: "",
        responseTime: "2020-07-17 11:13:27",
        lang: "zh_TW"
    },
    resFlag: '0',
    resMessage: {
        errorCode: "",
        errorMsg: ""
    },
    resContent: {
        'paginator': {
            'totalCount': '30',
            'pageSize': '5',
            'pageNumber': '2',
            'sortColName': 'fund1',
            'sortDirection': 'ASC'
        },
        isNetTrans: "true",
        roiDataList: [
            {
                "showStopBene": "2222",
                "licenno1": "07108000047",
                "unitCnt": "",
                "refProc": "22.00",
                "stopLoss": "90",
                "stopAppoBene": "",
                "osAmt": "11,000.00",
                "fund1": "0101",
                "appointDate": "109/07/30",
                "viewEngCurrency": "TWD",
                "fundName1": "摩根日本（日圓）",
                "acctRate": ".2888",
                "engCcy1": "JPY",
                "baseRoi": "",
                "viewChiCurrency": "台幣",
                "showStopLoss": "1111123",
                "chiCcy1": "日圓",
                "fundType": "單筆",
                "priceDate": "107/12/19",
                "orgRate": ".2965",
                "remark1": "申購尚未分配",
                "payCnt": "",
                "orgPrice": "",
                "stopBene": "100",
                "remark": "修改",
                "flag": "",
                "intretn": "542.00",
                "stopAutoBuy": "",
                "stopAppoLose": "",
                "apdint": "755.00",
                "date": "108/07/09",
                "nowPrice": "11,000.00",
                "acctPrice": "11,000.00",
                "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=0101&cfrom=NB",
                "key": "bHZIemo4cjlqTEFTekZiVlNhcUE2YjVXNjdHckdKcHJXJiQjIUE0NU9vcisxaERtOD0pojr3D"
            },
            {
                "showStopBene": "",
                "licenno1": "07108000048",
                "unitCnt": "",
                "refProc": ".00",
                "stopLoss": "",
                "stopAppoBene": "",
                "osAmt": "10,000.00",
                "fund1": "0101",
                "appointDate": "",
                "viewEngCurrency": "TWD",
                "fundName1": "摩根吐司（美圓）",
                "acctRate": ".2888",
                "engCcy1": "JPY",
                "baseRoi": "",
                "viewChiCurrency": "台幣",
                "showStopLoss": "",
                "chiCcy1": "日圓",
                "fundType": "單筆",
                "priceDate": "",
                "orgRate": ".2965",
                "remark1": "申購尚未分配",
                "payCnt": "",
                "orgPrice": "",
                "stopBene": "",
                "remark": "修改",
                "flag": "",
                "intretn": ".12",
                "stopAutoBuy": "",
                "stopAppoLose": "",
                "apdint": ".00",
                "date": "108/07/09",
                "nowPrice": "10,000.00",
                "acctPrice": "",
                "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=0101&cfrom=NB",
                "key": "d2VmMEY4M1BhNXRSd0VGR3BpYzdWYU43QVpEVHhYN3hXJiQjIUFqR3ZmVWJVdkZwZz0pojr3D"
            },
            {
                "showStopBene": "",
                "licenno1": "07108000049",
                "unitCnt": "",
                "refProc": ".00",
                "stopLoss": "",
                "stopAppoBene": "",
                "osAmt": "11,000.00",
                "fund1": "0101",
                "appointDate": "",
                "viewEngCurrency": "TWD",
                "fundName1": "摩根漢堡（韓圓）",
                "acctRate": ".2888",
                "engCcy1": "JPY",
                "baseRoi": "",
                "viewChiCurrency": "台幣",
                "showStopLoss": "",
                "chiCcy1": "日圓",
                "fundType": "單筆",
                "priceDate": "",
                "orgRate": ".2965",
                "remark1": "申購尚未分配",
                "payCnt": "",
                "orgPrice": "",
                "stopBene": "",
                "remark": "修改",
                "flag": "",
                "intretn": ".00",
                "stopAutoBuy": "",
                "stopAppoLose": "",
                "apdint": ".00",
                "date": "108/07/09",
                "nowPrice": "11,000.00",
                "acctPrice": "",
                "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=0101&cfrom=NB",
                "key": "eDhZbFVaY2NpaWlJc2V0elBHVkFRRjJoU0hMZlZWQkFXJiQjIUFyQWZLbDNEMGdxbz0pojr3D"
            },
            {
                "showStopBene": "",
                "licenno1": "07108000049",
                "unitCnt": "",
                "refProc": ".00",
                "stopLoss": "",
                "stopAppoBene": "",
                "osAmt": "11,000.00",
                "fund1": "0101",
                "appointDate": "",
                "viewEngCurrency": "TWD",
                "fundName1": "摩根炸雞（歐圓）",
                "acctRate": ".2888",
                "engCcy1": "JPY",
                "baseRoi": "",
                "viewChiCurrency": "台幣",
                "showStopLoss": "",
                "chiCcy1": "日圓",
                "fundType": "單筆",
                "priceDate": "",
                "orgRate": ".2965",
                "remark1": "申購尚未分配",
                "payCnt": "",
                "orgPrice": "",
                "stopBene": "",
                "remark": "修改",
                "flag": "",
                "intretn": ".00",
                "stopAutoBuy": "",
                "stopAppoLose": "",
                "apdint": ".00",
                "date": "108/07/09",
                "nowPrice": "11,000.00",
                "acctPrice": "",
                "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=0101&cfrom=NB",
                "key": "eDhZbFVaY2NpaWlJc2V0elBHVkFRRjJoU0hMZlZWQkFXJiQjIUFyQWZLbDNEMGdxbz0pojr3D"
            },
            {
                "showStopBene": "",
                "licenno1": "07108000049",
                "unitCnt": "",
                "refProc": ".00",
                "stopLoss": "",
                "stopAppoBene": "",
                "osAmt": "11,000.00",
                "fund1": "0101",
                "appointDate": "",
                "viewEngCurrency": "TWD",
                "fundName1": "摩根炒麵（澳圓）",
                "acctRate": ".2888",
                "engCcy1": "JPY",
                "baseRoi": "",
                "viewChiCurrency": "台幣",
                "showStopLoss": "",
                "chiCcy1": "日圓",
                "fundType": "單筆",
                "priceDate": "",
                "orgRate": ".2965",
                "remark1": "申購尚未分配",
                "payCnt": "",
                "orgPrice": "",
                "stopBene": "",
                "remark": "修改",
                "flag": "",
                "intretn": ".00",
                "stopAutoBuy": "",
                "stopAppoLose": "",
                "apdint": ".00",
                "date": "108/07/09",
                "nowPrice": "11,000.00",
                "acctPrice": "",
                "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=0101&cfrom=NB",
                "key": "eDhZbFVaY2NpaWlJc2V0elBHVkFRRjJoU0hMZlZWQkFXJiQjIUFyQWZLbDNEMGdxbz0pojr3D"
            }
        ],
        "infoDateStr": "2020/07/17  11：13：27  AM"
    },

};

let realData = {
    "apiId": "SPEC11060101",
    "token": {
        "requestId": "76cdce5720fafea51602490448196",
        "responseTime": "2020-10-12 16:13:50", "lang": "zh_TW"
    },
    "resFlag": "0",
    "resContent": {
        "isNetTrans": "true",
        "roiDataList": [{
            "showStopBene": "",
            "licenno1": "07106000067",
            "unitCnt": "",
            "refProc": ".00",
            "stopLoss": "",
            "stopAppoBene": "",
            "osAmt": "10,000.00",
            "appointDate": "",
            "viewEngCurrency": "TWD",
            "fundName1": "鋒裕環球生態A2美",
            "fundCode": "4811",
            "acctRate": "29.1000",
            "engCcy1": "USD",
            "baseRoi": "",
            "viewChiCurrency": "台幣",
            "showStopLoss": "",
            "chiCcy1": "美金",
            "fundType": "單筆",
            "priceDate": "",
            "orgRate": "30.2300",
            "remark1": "申購尚未分配",
            "payCnt": "",
            "orgPrice": "314.2500",
            "stopBene": "",
            "remark": "修改",
            "flag": "",
            "intretn": ".12",
            "stopAutoBuy": "",
            "stopAppoLose": "",
            "apdint": ".00",
            "date": "106/09/13",
            "nowPrice": "10,000.00",
            "acctPrice": "",
            "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=4811&cfrom=NB",
            "key": "b0ZkcGFSbXUxbVBiSkNhK24rK0hpelB2Y1ZQRm94QXFXJiQjIUFCMVByWjZ1L20yQT0pojr3D"
        },
        {
            "showStopBene": "5%",
            "licenno1": "07106000069",
            "unitCnt": "",
            "refProc": ".00",
            "stopLoss": "-5%",
            "stopAppoBene": "",
            "osAmt": "10,000.00",
            "appointDate": "109/03/25",
            "viewEngCurrency": "TWD",
            "fundName1": "摩根日本（日圓）",
            "fundCode": "0101",
            "acctRate": ".2746",
            "engCcy1": "JPY",
            "baseRoi": "",
            "viewChiCurrency": "台幣",
            "showStopLoss": "不適用",
            "chiCcy1": "日圓",
            "fundType": "單筆",
            "priceDate": "",
            "orgRate": ".2680",
            "remark1": "申購尚未分配",
            "payCnt": "",
            "orgPrice": "26495.8300",
            "stopBene": "5%",
            "remark": "修改",
            "flag": "",
            "intretn": "1.00",
            "stopAutoBuy": "",
            "stopAppoLose": "",
            "apdint": ".00",
            "date": "106/09/14",
            "nowPrice": "10,000.00",
            "acctPrice": "",
            "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=0101&cfrom=NB",
            "key": "aEN6aUlibEt0U0Zkb3N1TTR5WGdacWU5Q1c5SWw2RTVXJiQjIUF5c2hzc2FyQzVzST0pojr3D"
        },
        {
            "showStopBene": "",
            "licenno1": "07106003953",
            "unitCnt": "",
            "refProc": ".00",
            "stopLoss": "",
            "stopAppoBene": "",
            "osAmt": "10,000.00",
            "appointDate": "",
            "viewEngCurrency": "TWD",
            "fundName1": "鋒裕環球生態A2美",
            "fundCode": "4811",
            "acctRate": "29.1000",
            "engCcy1": "USD",
            "baseRoi": "",
            "viewChiCurrency": "台幣",
            "showStopLoss": "",
            "chiCcy1": "美金",
            "fundType": "單筆",
            "priceDate": "",
            "orgRate": "30.1900",
            "remark1": "申購尚未分配",
            "payCnt": "",
            "orgPrice": "314.2500",
            "stopBene": "",
            "remark": "修改",
            "flag": "",
            "intretn": "-3.00",
            "stopAutoBuy": "",
            "stopAppoLose": "",
            "apdint": ".00",
            "date": "106/10/30",
            "nowPrice": "10,000.00",
            "acctPrice": "",
            "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=4811&cfrom=NB",
            "key": "ckFKYnpOMmhaaTlNVDJxUVlOQUR2NTltNnVRZFdrcWhXJiQjIUFvM1JDRmVBWHBrUT0pojr3D"
        },
        {
            "showStopBene": "",
            "licenno1": "07106003954",
            "unitCnt": "",
            "refProc": ".00",
            "stopLoss": "",
            "stopAppoBene": "",
            "osAmt": "10,000.00",
            "appointDate": "",
            "viewEngCurrency": "TWD",
            "fundName1": "鋒裕環球生態A2美",
            "fundCode": "4811",
            "acctRate": "29.1000",
            "engCcy1": "USD",
            "baseRoi": "",
            "viewChiCurrency": "台幣",
            "showStopLoss": "",
            "chiCcy1": "美金",
            "fundType": "單筆",
            "priceDate": "",
            "orgRate": "30.1900",
            "remark1": "申購尚未分配",
            "payCnt": "",
            "orgPrice": "314.2500",
            "stopBene": "",
            "remark": "修改",
            "flag": "",
            "intretn": "+5",
            "stopAutoBuy": "",
            "stopAppoLose": "",
            "apdint": ".00",
            "date": "106/10/30",
            "nowPrice": "10,000.00",
            "acctPrice": "",
            "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=4811&cfrom=NB",
            "key": "V3dYbXdNdzREMXhKQlo4T3c0RXVxcTQvVHRhWnh6Z0VXJiQjIUFUWlpmSDBGRGdEaz0pojr3D"
        },
        {
            "showStopBene": "",
            "licenno1": "07106003955",
            "unitCnt": "",
            "refProc": ".00",
            "stopLoss": "",
            "stopAppoBene": "",
            "osAmt": "10,000.00",
            "appointDate": "",
            "viewEngCurrency": "TWD",
            "fundName1": "鋒裕環球生態A2美",
            "fundCode": "4811",
            "acctRate": "29.1000",
            "engCcy1": "USD",
            "baseRoi": "",
            "viewChiCurrency": "台幣",
            "showStopLoss": "",
            "chiCcy1": "美金",
            "fundType": "單筆",
            "priceDate": "",
            "orgRate": "30.1900",
            "remark1": "申購尚未分配",
            "payCnt": "",
            "orgPrice": "314.2500",
            "stopBene": "",
            "remark": "修改",
            "flag": "",
            "intretn": ".00",
            "stopAutoBuy": "",
            "stopAppoLose": "",
            "apdint": ".00",
            "date": "106/10/30",
            "nowPrice": "10,000.00",
            "acctPrice": "",
            "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=4811&cfrom=NB",
            "key": "dURHb2RsL3lKekRZSEwwVm5KUGE1aFR6UHBveUtMMlBXJiQjIUF1dE1Vb09JeEFEbz0pojr3D"
        },
        {
            "showStopBene": "",
            "licenno1": "07106003956",
            "unitCnt": "",
            "refProc": ".00",
            "stopLoss": "",
            "stopAppoBene": "",
            "osAmt": "10,000.00",
            "appointDate": "",
            "viewEngCurrency": "TWD",
            "fundName1": "鋒裕環球生態A2美",
            "fundCode": "4811",
            "acctRate": "29.1000",
            "engCcy1": "USD",
            "baseRoi": "",
            "viewChiCurrency": "台幣",
            "showStopLoss": "",
            "chiCcy1": "美金",
            "fundType": "單筆",
            "priceDate": "",
            "orgRate": "30.1900",
            "remark1": "申購尚未分配",
            "payCnt": "",
            "orgPrice": "314.2500",
            "stopBene": "",
            "remark": "修改",
            "flag": "",
            "intretn": "0.00",
            "stopAutoBuy": "",
            "stopAppoLose": "",
            "apdint": ".00",
            "date": "106/10/30",
            "nowPrice": "10,000.00",
            "acctPrice": "",
            "scsbFundUrl": "http://fund.scsb.com.tw/Fund/effect_visit_netbank.jsp?fund_code=4811&cfrom=NB",
            "key": "SEFwMi9abVhLWVVXdHc3alJ3eE45ZXpySCsrSXNmOG5XJiQjIUFqd0Mwc1BOUUFLTT0pojr3D"
        }],
        "infoDateStr": "2020/10/12  04：13：55  PM",
        "paginator": {
            "totalCount": "19",
            "pageSize": "6",
            "pageNumber": "1",
            "sortColName": "fund1",
            "sortDirection": "DESC"
        }
    }
};
let data1M = {};
let dataEmpty = {
    apiId: "SPEC11060101",
    token: {
        requestId: "",
        responseTime: "2020-07-17 11:13:27",
        lang: "zh_TW"
    },
    resFlag: '0',
    resMessage: {
        errorCode: "",
        errorMsg: ""
    },
    resContent: {
        outputData: [
            {
                isNetTrans: "true",
                roiDataList: [

                ],
                "infoDateStr": "2020/07/17  11：13：27  AM"
            }
        ]
    }
};

let df_response = {};

export const api_response = { ...df_response, ...realData };
export const api_empty = { ...df_response, ...dataEmpty };
export const api_error = {
    apiId: 'SPEC11060101',
    token: {
        requestId: '',
        responseTime: '2020-06-20 18:18:31',
        lang: 'zh_TW'
    },
    resFlag: '1',
    resMessage: {
        errorCode: 'ERRAAAAAAA',
        errorMsg: 'Test Error'
    }
};
export const api_exception = {
    errorCode: 'ERRAAAAAAA',
    errorMsg: 'Test Error'
};
