/**
 * 模擬api
 */

let response = {

    "apiId": "SPEC11010201",
    "token": {
        "requestId": "36a940a93e8c7f371597046243346",
        "responseTime": "2020-08-10 15:57:23",
        "lang": "zh_TW"
    },
    "resFlag": "0",
    "resMessage": {
        "errorCode": "",
        "errorMsg": ""
    },
    "resContent": {
        "roiData": [
            {
                "date": "108/01/24",
                "acctRate": "",
                "viewCurrencyeng": "USD",
                "orgRate": "",
                "payCnt": "",
                "orgPrice": "",
                "roi": "0.00",
                "appointDate": "",
                "viewCurrencychi": "美金",
                "fundType": "單筆",
                "nowPrice": "300,000.00",
                "priceDate": "108/01/24",
                "osAmt": "300,000.00",
                "fundCode": "FJ04",
                "stopAppoBene": "Y",
                "licenno1": "02508000004",
                "key": "b01CQkU5QjlOb1h6ODFjeFZTcVVMRDZyemlrd2t5NmRXJiQjIUE4Sis0cE1aWXFLWT0pojr3D",
                "engCcy1": "TWD",
                "apdint": "0.00",
                "intretn": "0.00",
                "chiccy1": "美金",
                "profitLoss": "---",
                "acctPrice": "111111",
                "unitCnt": "",
                "stopAppoLoss": "Y",
                "stopBene": "",
                "stopLoss": "",
                "fundName1": "美國大型價值A美",
                "remark1": "申購尚未分配",
                "fundFlag": "*"
            },
            {
                "date": "108/01/14",
                "acctRate": "",
                "viewCurrencyeng": "AUD",
                "orgRate": "",
                "payCnt": "",
                "orgPrice": "8.7200",
                "roi": "0.00",
                "appointDate": "",
                "viewCurrencychi": "澳幣",
                "fundType": "單筆",
                "nowPrice": "3,244.00",
                "priceDate": "",
                "osAmt": "3,244.00",
                "fundCode": "F502",
                "stopAppoBene": "",
                "licenno1": "24508000002",
                "key": "OEpGZXhBTnNaelIzZ21NRFFsMW5VazJOYklQV25IZ2tXJiQjIUE5WWl5UHpzM3VXST0pojr3D",
                "engCcy1": "AUD",
                "apdint": "0.00",
                "intretn": "0.00",
                "chiccy1": "澳幣",
                "profitLoss": "---",
                "acctPrice": "",
                "unitCnt": "",
                "stopAppoLoss": "",
                "stopBene": "",
                "stopLoss": "",
                "fundName1": "安聯收益成長AM澳現",
                "remark1": "申購尚未分配",
                "fundFlag": "*"
            },
            {
                "date": "108/04/17",
                "acctRate": "29.9900",
                "viewCurrencyeng": "NTD",
                "orgRate": "30.8600",
                "payCnt": "",
                "orgPrice": "8.8200",
                "roi": "0.00",
                "appointDate": "",
                "viewCurrencychi": "台幣",
                "fundType": "單筆",
                "nowPrice": "10,000.00",
                "priceDate": "",
                "osAmt": "10,000.00",
                "fundCode": "F501",
                "stopAppoBene": "",
                "licenno1": "07108000010",
                "key": "T1RmR0xnckhDV0lLcllOSzBqa0ZIdUI2YTk4SGlWMVZXJiQjIUF3eTRsZ3pUd0VVRT0pojr3D",
                "engCcy1": "USD",
                "apdint": "0.00",
                "intretn": "0.00",
                "chiccy1": "美金",
                "profitLoss": "---",
                "acctPrice": "",
                "unitCnt": "",
                "stopAppoLoss": "",
                "stopBene": "",
                "stopLoss": "",
                "fundName1": "安聯收益成長AM美現",
                "remark1": "申購尚未分配",
                "fundFlag": "*"
            },
            {
                "date": "108/01/14",
                "acctRate": "",
                "viewCurrencyeng": "USD",
                "orgRate": "",
                "payCnt": "",
                "orgPrice": "8.8200",
                "roi": "0.00",
                "appointDate": "",
                "viewCurrencychi": "美金",
                "fundType": "單筆",
                "nowPrice": "5,219.00",
                "priceDate": "",
                "osAmt": "5,219.00",
                "fundCode": "F501",
                "stopAppoBene": "",
                "licenno1": "24508000001",
                "key": "dXJ4WjVlM0F0OGtKSmxjbFZJY2VvMjVTalZBUzUwOXhXJiQjIUFlM1hlZkd3RzRDQT0pojr3D",
                "engCcy1": "USD",
                "apdint": "0.00",
                "intretn": "0.00",
                "chiccy1": "美金",
                "profitLoss": "---",
                "acctPrice": "",
                "unitCnt": "",
                "stopAppoLoss": "",
                "stopBene": "",
                "stopLoss": "",
                "fundName1": "安聯收益成長AM美現",
                "remark1": "申購尚未分配",
                "fundFlag": "*"
            },
            {
                "date": "107/12/14",
                "acctRate": "",
                "viewCurrencyeng": "USD",
                "orgRate": "",
                "payCnt": "",
                "orgPrice": "10.0000",
                "roi": "-4.20",
                "appointDate": "",
                "viewCurrencychi": "美金",
                "fundType": "單筆",
                "nowPrice": "335,300.00",
                "loss": "-3",
                "priceDate": "107/12/28",
                "osAmt": "350,000.00",
                "fundCode": "9C99",
                "stopAppoBene": "Y",
                "profit": "1",
                "licenno1": "02507000041",
                "key": "V29xS3l1TDV0N2VqOEJyTjJtNkNnQStsSllHWFFxZ3lXJiQjIUFmVUEwNThCdm8rND0pojr3D",
                "engCcy1": "USD",
                "apdint": "0.00",
                "intretn": "-4.20",
                "chiccy1": "美金",
                "profitLoss": "LOSS",
                "acctPrice": "9.5800",
                "unitCnt": "35,000.0000",
                "stopAppoLoss": "Y",
                "stopBene": "",
                "stopLoss": "",
                "fundName1": "聯邦全球高息策略美現",
                "remark1": "贖回尚未解款",
                "fundFlag": "*"
            }
        ],
        "totalNoproc": "-1,289,640",
        "totalBaochou": "-0.1",
        "totalTotosamt": "1,355,656,107",
        "sumUpInfo": {
            "totEngccy": "折台",
            "noProc": "-1,290,311.00",
            "totChiccy": "折台",
            "totsAmt": "1,390,595,816.00",
            "totprice": "1,389,305,505.00",
            "baoChou": "-0.09"
        },
        "totalTotprice": "1,354,366,466",
        "paginator": {
            "totalCount": "75",
            "pageSize": "5",
            "pageNumber": "1",
            "sortColName": "fundCode",
            "sortDirection": "DESC"
        }
    }
};

let realData = {
    "apiId":"SPEC11010201",
    "token":{
       "requestId":"d5aae51a5f26068f1603335180088",
       "responseTime":"2020-10-22 10:52:34",
       "lang":"zh_TW"
    },
    "resFlag":"0",
    "resMessage":{
       "errorCode":"",
       "errorMsg":""
    },
    "resContent":{
       "roiData":[
          {
             "date":"106/09/13",
             "acctRate":"28.6100",
             "viewCurrencyeng":"NTD",
             "orgRate":"30.2300",
             "payCnt":"",
             "orgPrice":"314.2500",
             "roi":"0.00",
             "appointDate":"109/10/20",
             "viewCurrencychi":"台幣",
             "fundType":"單筆",
             "nowPrice":"10,000.00",
             "loss":"",
             "priceDate":"",
             "fundCode":"4811",
             "osAmt":"10,000.00",
             "fundFlag":"",
             "stopAppoBene":"",
             "profit":"",
             "licenno1":"07106000067",
             "key":"W0JAMzZkNDZkMjVXJiQjIUFbQkAxMDNiYjkxMwpojr3Dpojr3D",
             "engCcy1":"USD",
             "apdint":"0.00",
             "intretn":"0.00",
             "chiccy1":"美金",
             "profitLoss":"NA",
             "acctPrice":"",
             "unitCnt":"",
             "stopAppoLoss":"",
             "stopBene":"20%",
             "stopLoss":"-15%",
             "fundName1":"鋒裕環球生態A2美",
             "remark1":"申購尚未分配"
          },
          {
             "date":"106/10/30",
             "acctRate":"28.6100",
             "viewCurrencyeng":"USD",
             "orgRate":"30.1900",
             "payCnt":"",
             "orgPrice":"314.2500",
             "roi":"0.00",
             "appointDate":"",
             "viewCurrencychi":"美金",
             "fundType":"單筆",
             "nowPrice":"10,000.00",
             "loss":"",
             "priceDate":"",
             "fundCode":"4811",
             "osAmt":"10,000.00",
             "fundFlag":"",
             "stopAppoBene":"",
             "profit":"",
             "licenno1":"07506003953",
             "key":"W0JANGQ2MDU2NDFXJiQjIUFbQkA2OWNjMGNlNwpojr3Dpojr3D",
             "engCcy1":"USD",
             "apdint":"0.00",
             "intretn":"0.00",
             "chiccy1":"美金",
             "profitLoss":"NA",
             "acctPrice":"",
             "unitCnt":"",
             "stopAppoLoss":"",
             "stopBene":"",
             "stopLoss":"",
             "fundName1":"鋒裕環球生態A2美",
             "remark1":"申購尚未分配"
          },
          {
             "date":"106/10/30",
             "acctRate":"28.6100",
             "viewCurrencyeng":"NTD",
             "orgRate":"30.1900",
             "payCnt":"",
             "orgPrice":"314.2500",
             "roi":"0.00",
             "appointDate":"",
             "viewCurrencychi":"台幣",
             "fundType":"單筆",
             "nowPrice":"10,000.00",
             "loss":"",
             "priceDate":"",
             "fundCode":"4811",
             "osAmt":"10,000.00",
             "fundFlag":"",
             "stopAppoBene":"",
             "profit":"",
             "licenno1":"07106003954",
             "key":"W0JANTJmYmUwMDhXJiQjIUFbQkAxZGU2NzY0OApojr3Dpojr3D",
             "engCcy1":"USD",
             "apdint":"0.00",
             "intretn":"0.00",
             "chiccy1":"美金",
             "profitLoss":"NA",
             "acctPrice":"",
             "unitCnt":"",
             "stopAppoLoss":"",
             "stopBene":"",
             "stopLoss":"",
             "fundName1":"鋒裕環球生態A2美",
             "remark1":"申購尚未分配"
          },
          {
             "date":"106/10/30",
             "acctRate":"28.6100",
             "viewCurrencyeng":"NTD",
             "orgRate":"30.1900",
             "payCnt":"",
             "orgPrice":"314.2500",
             "roi":"0.00",
             "appointDate":"",
             "viewCurrencychi":"台幣",
             "fundType":"單筆",
             "nowPrice":"10,000.00",
             "loss":"",
             "priceDate":"",
             "fundCode":"4811",
             "osAmt":"10,000.00",
             "fundFlag":"",
             "stopAppoBene":"",
             "profit":"",
             "licenno1":"07106003955",
             "key":"W0JANzBjM2JhODZXJiQjIUFbQkA3ZDM1ZWYzNgpojr3Dpojr3D",
             "engCcy1":"USD",
             "apdint":"0.00",
             "intretn":"0.00",
             "chiccy1":"美金",
             "profitLoss":"NA",
             "acctPrice":"",
             "unitCnt":"",
             "stopAppoLoss":"",
             "stopBene":"",
             "stopLoss":"",
             "fundName1":"鋒裕環球生態A2美",
             "remark1":"申購尚未分配"
          },
          {
             "date":"106/10/30",
             "acctRate":"28.6100",
             "viewCurrencyeng":"NTD",
             "orgRate":"30.1900",
             "payCnt":"",
             "orgPrice":"314.2500",
             "roi":"0.00",
             "appointDate":"",
             "viewCurrencychi":"台幣",
             "fundType":"單筆",
             "nowPrice":"10,000.00",
             "loss":"",
             "priceDate":"",
             "fundCode":"4811",
             "osAmt":"10,000.00",
             "fundFlag":"",
             "stopAppoBene":"",
             "profit":"",
             "licenno1":"07106003956",
             "key":"W0JANjA2OTRmNzJXJiQjIUFbQkBkMTNkZTcz",
             "engCcy1":"USD",
             "apdint":"0.00",
             "intretn":"0.00",
             "chiccy1":"美金",
             "profitLoss":"NA",
             "acctPrice":"",
             "unitCnt":"",
             "stopAppoLoss":"",
             "stopBene":"",
             "stopLoss":"",
             "fundName1":"鋒裕環球生態A2美",
             "remark1":"申購尚未分配"
          },
          {
             "date":"106/10/30",
             "acctRate":"28.6100",
             "viewCurrencyeng":"NTD",
             "orgRate":"30.1900",
             "payCnt":"",
             "orgPrice":"314.2500",
             "roi":"0.00",
             "appointDate":"",
             "viewCurrencychi":"台幣",
             "fundType":"單筆",
             "nowPrice":"10,000.00",
             "loss":"",
             "priceDate":"",
             "fundCode":"4811",
             "osAmt":"10,000.00",
             "fundFlag":"",
             "stopAppoBene":"",
             "profit":"",
             "licenno1":"07106003957",
             "key":"W0JANzBmYTdkNTVXJiQjIUFbQkA1YWMyYWVlNwpojr3Dpojr3D",
             "engCcy1":"USD",
             "apdint":"0.00",
             "intretn":"0.00",
             "chiccy1":"美金",
             "profitLoss":"NA",
             "acctPrice":"",
             "unitCnt":"",
             "stopAppoLoss":"",
             "stopBene":"",
             "stopLoss":"",
             "fundName1":"鋒裕環球生態A2美",
             "remark1":"申購尚未分配"
          }
       ],
       "totalNoproc":"1,388",
       "totalBaochou":"0.97",
       "totalTotosamt":"143,640",
       "sumUpInfo":{
          "totEngccy":"折台",
          "noProc":"1,367.00",
          "totChiccy":"折台",
          "totsAmt":"142,105.00",
          "totprice":"143,472.00",
          "baoChou":"0.96"
       },
       "totalTotprice":"145,028",
       "paginator":{
          "totalCount":"13",
          "pageSize":"6",
          "pageNumber":"1",
          "sortColName":"fundCode",
          "sortDirection":"DESC"
       }
    }
 };

let df_response = {};

export const api_response = { ...df_response, ...realData };
// export const api_empty = { ...df_response, ...dataEmpty };
export const api_error = {
    apiId: 'SPEC06010102',
    token: {
        requestId: '',
        responseTime: '2020-06-20 18:18:31',
        lang: 'zh_TW'
    },
    resFlag: '1',
    resMessage: {
        errorCode: 'ERRAAAAAAA',
        errorMsg: 'Test Error'
    }
};
export const api_exception = {
    errorCode: 'ERRAAAAAAA',
    errorMsg: 'Test Error'
};
